[project]
name = "dankert-download"
version = "0.1.0"
description = "Мощный загрузчик видео от DanKert, альтернатива yt-dlp"
authors = [{name = "DanKert"}]
dependencies = [
    "requests"
]
requires-python = ">=3.7"

[project.scripts]
dankert_download = "dankert_download.__main__:main"
